App\Entity\PostDto:
  attributes:
      id:
        groups : ['post']
      title:
        groups : ['post']
      content:
        groups : ['post']
      type_id:
        groups : ['post']
      shopRelated_id:
        groups : ['post']
      image:
        groups : ['post']

